"""The second dashboard: adherence grouped by month, event context, and schedule.

Build step 3. A self-contained HTML page, the companion to the weekly dashboard.
It reads the three grouping views and shows, for each grouping, a table of
planned and actual minutes, the week count, an adherence ratio, and a two-bar
meter. It reuses the weekly dashboard's style, so the two pages read as one.

Public functions:
    :func:`seasons_html`   return the dashboard HTML as a string
    :func:`write_seasons`  render and write it to a file
"""

from __future__ import annotations

from .compare import queries
from .dashboard import STYLE, SCRIPT, _esc, _fmt2, _meter, _ratio


def _section(title, subtitle, label_head, rows, label_key, empty) -> list:
    """Return the lines for one grouping table.

    ROWS are view rows, LABEL_KEY names the group column, and EMPTY is the
    message shown when there are no rows.
    """
    if not rows:
        return [f"  <h2>{_esc(title)}</h2>", f'  <p class="sub">{_esc(empty)}</p>']
    scale = 0
    for r in rows:
        scale = max(scale, r["planned_min"], r["actual_min"])
    out = [
        f"  <h2>{_esc(title)}</h2>",
        f'  <p class="sub">{_esc(subtitle)}</p>',
        "  <table>",
        f'    <thead><tr><th>{_esc(label_head)}</th>'
        '<th class="num">Weeks</th><th class="num">Planned</th>'
        '<th class="num">Actual</th><th>Progress</th>'
        '<th class="num">Adherence</th></tr></thead>',
        "    <tbody>",
    ]
    for r in rows:
        out.append(
            f'      <tr><td>{_esc(r[label_key])}</td>'
            f'<td class="num">{r["weeks"]}</td>'
            f'<td class="num">{r["planned_min"]}</td>'
            f'<td class="num">{r["actual_min"]}</td>'
            f'<td>{_meter(r["planned_min"], r["actual_min"], scale)}</td>'
            f'<td class="num">{_fmt2(r["adherence"])}</td></tr>'
        )
    out.append("    </tbody>")
    out.append("  </table>")
    return out


def seasons_html(con) -> str:
    """Return the self-contained grouped-adherence dashboard HTML."""
    months = queries.month_overall(con)
    contexts = queries.context_overall(con)
    schedules = queries.schedule_overall(con)

    planned_total = sum(r["planned_min"] for r in months)
    actual_total = sum(r["actual_min"] for r in months)
    week_total = sum(r["weeks"] for r in months)

    lines = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '  <meta charset="utf-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1">',
        "  <title>Writing seasons: grouped adherence</title>",
        STYLE,
        "</head>",
        '<body class="wh">',
        '  <div class="wrap">',
        "  <header>",
        '    <div><h1>Writing seasons</h1><p class="sub">Grouped adherence by month,'
        " context, and schedule</p></div>",
        '    <button id="wh-theme" class="toggle" type="button">Dark theme</button>',
        "  </header>",
        '  <section class="tiles">',
        f'    <div class="tile"><div class="v">{week_total}</div><div class="k">weeks recorded</div></div>',
        f'    <div class="tile"><div class="v">{planned_total}</div><div class="k">planned minutes</div></div>',
        f'    <div class="tile"><div class="v">{actual_total}</div><div class="k">actual minutes</div></div>',
        f'    <div class="tile"><div class="v">{_ratio(actual_total, planned_total)}</div><div class="k">overall adherence</div></div>',
        "  </section>",
    ]
    lines += _section(
        "By month",
        "Seasonal trend in adherence across the calendar.",
        "Month", months, "month",
        "No weeks recorded yet.")
    lines += _section(
        "By event context",
        "Adherence in weeks tagged with an event, for example a meeting, teaching, or data collection.",
        "Context", contexts, "tag",
        "No context tags recorded. Set one with: writing-habit context set --week DATE --tag teaching.")
    lines += _section(
        "By schedule",
        "Adherence grouped by the schedule file-name code, so plan shapes can be compared.",
        "Schedule", schedules, "schedule_code",
        "No schedule codes recorded. They are captured at plan import from the table file name.")
    lines += [
        '  <p class="foot">Generated by writing-habit from the shared SQLite'
        " database. Planned versus actual, self-reported effort.</p>",
        "  </div>",
        SCRIPT,
        "</body>",
        "</html>",
        "",
    ]
    return "\n".join(lines)


def write_seasons(con, out_path: str) -> str:
    """Render the seasons dashboard and write it to OUT-PATH."""
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(seasons_html(con))
    return out_path
